apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: Frontend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      type: Frontend
  template:
    metadata:
      labels:
        app: myapp
        type: Frontend   # ✅ fixed typo here
    spec:
      containers:        # ✅ fixed indentation
        - name: myapp-container
          image: nginx

