apiVersion: v1
kind: Service
metadata:
  name: demo-svc-for-frontend
  labels:
    app: frontend
    type: 
spec:
  type: NodePort
  selector: 
    type: Frontend
  ports: 
   - port: 80
     targetPort: 80
     nodePort: 30002
